version: "2.0"
services:
  akash-task:
    image: devkush/akashv1:latest
    expose:
      - port: 80
        as: 80
        to:
          - global: true

profiles:
  compute:
    akash-task:
      resources:
        cpu:
          units: 0.1
        memory:
          size: 512Mi
        storage:
          size: 512Mi
  placement:
    dcloud:
      pricing:
        akash-task:
          denom: uakt
          amount: 1000

deployment:
  akash-task:
    dcloud:
      profile: akash-task
      count: 1
